name: Doc

env:
  GITHUB_ACTOR: michaelb
  GITHUB_REPOSITORY: michaelb/sniprun
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: 
  push:
    branches: [ master ]
  workflow_dispatch:


permissions: {}

jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "doc/build.sh"
        shell: bash
