name: Rust

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master, dev]
  workflow_dispatch:

jobs:
  ci-safety:
    name: ci-safety
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v4
      - name: run zizmor ci analysis tool
        run: uvx zizmor --format sarif . > results.sarif 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: zizmor

  build:
    name : build-latest-stable
    runs-on: ubuntu-20.04
    # version used in release process to guarantee old-GLIBC compatibility

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Build
      run: cargo build --verbose --release --target x86_64-unknown-linux-gnu 

  buildmsrv:
    name: build-msrv
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust 1.65 toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65
          override: true
      - name: build
        run: cargo build --release --locked

  buildnightly:
    name: build-nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: build
        run: cargo build --release --target x86_64-unknown-linux-gnu 

  unittest:
    name: unit & integration tests
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - run: './ressources/install_all_compilers_ci.sh'

    - uses: oven-sh/setup-bun@v1

    - uses: dlang-community/setup-dlang@v1

    - uses: erlef/setup-beam@v1
      with:
        otp-version: "23"
        elixir-version: "1.14"


    - name: Unit tests
      run: cargo test --release --features ignore_in_ci

    - name: integration tests
      run: cargo test --release --features ignore_in_ci --test integration

  install:
    name: install (download)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: installation tests
      run: ./install.sh
